name: Zola on GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # - cron: '0 0 * * *' # Runs at 00:00 UTC daily
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
    if: (github.event_name == 'pull_request' || github.event_name == 'schedule') && github.ref != 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build only
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_DIR: .
          BUILD_ONLY: true

  build_and_deploy:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_DIR: .
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}